runtime: nodejs14
env_variables:
  FACEBOOK_CALLBACK: https://alien-fold-347804.de.r.appspot.com/auth/facebook/callback
  FACEBOOK_ID: process.env.FACEBOOK_ID
  FACEBOOK_SECRET: process.env.FACEBOOK_SECRET
  MONGODB_URI: process.env.MONGODB_URI_FOR_DEPLOYMENT
  SESSION_SECRET: ThisIsHerokuSecret